version: '3.8'

services:
  # Base de Datos MySQL
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - castanedatech-network

  # Laravel App & PHP-FPM
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: castanedatech-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - castanedatech-network
    depends_on:
      - db

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - castanedatech-network
    depends_on:
      - app

  # Socket Server (Node.js)
  sockets:
    build:
      context: .
      dockerfile: Dockerfile.sockets
    image: castanedatech-sockets
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      - castanedatech-network

networks:
  castanedatech-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400

volumes:
  dbdata: