version: '3.8'

services:
  # Laravel App & PHP-FPM
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: castanedatech-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - SOCKET_SERVER_URL=http://sockets:3001
      - VITE_SOCKET_URL=https://castanedatech.com # User will need to change this
    networks:
      - castanedatech-network

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - castanedatech-network
    depends_on:
      - app

  # Socket Server (Node.js)
  sockets:
    build:
      context: .
      dockerfile: Dockerfile.sockets
    image: castanedatech-sockets
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      - castanedatech-network

networks:
  castanedatech-network:
    driver: bridge
